DROP DATABASE IF EXISTS AtlasWeaponShop;
CREATE DATABASE IF NOT EXISTS AtlasWeaponShop;
SHOW DATABASES;
USE AtlasWeaponShop;

DROP TABLE IF EXISTS Supplier;
CREATE TABLE IF NOT EXISTS Supplier(
    SupplierId VARCHAR(15),
    SupplierName VARCHAR(30),
    SupplierPayment INT DEFAULT 0,
    ItemQty INT DEFAULT 0,
    ItemPrice DOUBLE DEFAULT 0.00,
    SupplyItem VARCHAR(30),
    CONSTRAINT PRIMARY KEY (SupplierId)
    );
SHOW TABLES;
DESCRIBE Supplier;


DROP TABLE IF EXISTS Model;
CREATE TABLE IF NOT EXISTS Model(
    ModelId VARCHAR(15),
    ModelName VARCHAR(30),
    CONSTRAINT PRIMARY KEY (ModelId)
    );
SHOW TABLES;
DESCRIBE Model;


DROP TABLE IF EXISTS Category;
CREATE TABLE IF NOT EXISTS Category(
    CategoryId VARCHAR(15),
    CategoryName VARCHAR(30),
    CONSTRAINT PRIMARY KEY (CategoryId)
    );
SHOW TABLES;
DESCRIBE Category;


DROP TABLE IF EXISTS Item;
CREATE TABLE IF NOT EXISTS Item(
    ItemId VARCHAR(15),
    CategoryId VARCHAR(15),
    ModelId VARCHAR(15),
    SupplierId VARCHAR(15),
    Price DOUBLE DEFAULT 0.00,
    ItemName VARCHAR(30),
    QtyOnHand INT DEFAULT 0,
    CONSTRAINT PRIMARY KEY (ItemId),
    CONSTRAINT FOREIGN KEY(CategoryId)REFERENCES Category(CategoryId)ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(ModelId)REFERENCES Model(ModelId)ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(SupplierId)REFERENCES Supplier(SupplierId)ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES;
DESCRIBE Item;


DROP TABLE IF EXISTS TrainingGround;
CREATE TABLE IF NOT EXISTS TrainingGround(
    UserId VARCHAR(15),
    RowNumber INT DEFAULT 0,
    RowUserName VARCHAR(15),
    UsingGunName VARCHAR(15),
    UsingGunType VARCHAR(15),
    CONSTRAINT PRIMARY KEY (UserId)
    );
SHOW TABLES;
DESCRIBE TrainingGround;


DROP TABLE IF EXISTS Customer;
CREATE TABLE IF NOT EXISTS Customer(
    CustomerId VARCHAR(15),
    CustomerName VARCHAR(15),
    CustomerNic VARCHAR(15),
    TelephoneNumber INT(10),
    CustomerAddress VARCHAR(30),
    CustomerLicenseNumber VARCHAR(15),
    CONSTRAINT PRIMARY KEY (CustomerId)

    );
SHOW TABLES;
DESCRIBE Customer;


DROP TABLE IF EXISTS `Order`;
CREATE TABLE IF NOT EXISTS `Order`(
    OrderId VARCHAR(15),
    CustomerId VARCHAR(15),
    OrderDate DATE,
    CONSTRAINT PRIMARY KEY (OrderId),
    CONSTRAINT FOREIGN KEY (CustomerId)REFERENCES Customer(CustomerId)ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES;
DESCRIBE `Order`;



DROP TABLE IF EXISTS `OrderDetails`;
CREATE TABLE IF NOT EXISTS `OrderDetails`(
    ItemId VARCHAR(15),
    OrderId VARCHAR(15),
    OrderQty INT DEFAULT 0,
    CONSTRAINT PRIMARY KEY (ItemId,OrderId),
    CONSTRAINT FOREIGN KEY (ItemId)REFERENCES Item(ItemId)ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (OrderId)REFERENCES `Order`(OrderId)ON DELETE CASCADE ON UPDATE CASCADE
    );
SHOW TABLES;
DESCRIBE `OrderDetails`;


DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User`(
    UserName VARCHAR(15),
    Name VARCHAR(30),
    UserPassword VARCHAR(100),
    Role VARCHAR(15),
    Address VARCHAR(30),
    CONSTRAINT PRIMARY KEY (UserName)
    );
SHOW TABLES;
DESCRIBE `User`;


DROP TABLE IF EXISTS Login;
CREATE TABLE IF NOT EXISTS Login(
    LoginId VARCHAR(15),
    UserName VARCHAR(15),
    UserPassword VARCHAR(100),
    CONSTRAINT PRIMARY KEY (LoginId)
    );
SHOW TABLES;
DESCRIBE Login;
